export const weapons = [
    // Inner Sphere
    {BTCode: "IS_SL", name: "Heavy Infantry Laser", code: "HIL", range: "6-18/36", pen: 5, traits: ["AI", "Burst: 1"], category: "Advanced"},
    {BTCode: "IS_ML", name: "Very Light Laser Cannon", code: "VLLC", range: "8-24/48", pen: 7, traits: ["Precise"], category: "Advanced"},
    {BTCode: "IS_LL", name: "Medium Laser Cannon", code: "MLC", range: "12-36/72", pen: 9, traits: ["Precise"], category: "Advanced"},
    {BTCode: "IS_SPL", name: "Very Very Light Pulse Laser", code: "VVLPL", range: "4-12/24", pen: 5, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "IS_MPL", name: "Very Light Pulse Laser", code: "VLPL", range: "6-18/36", pen: 8, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "IS_LPL", name: "Medium Pulse Laser", code: "MPL", range: "12-24/48", pen: 10, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "IS_ERSL", name: "Heavy Infantry Laser", code: "HIL", range: "0-24/42", pen: 5, traits: ["AI", "Burst: 1"], category: "Advanced"},
    {BTCode: "IS_ERML", name: "Very Light Laser Cannon", code: "VLLC", range: "2-30/54", pen: 7, traits: ["Precise"], category: "Advanced"},
    {BTCode: "IS_ERLL", name: "Medium Laser Cannon", code: "MLC", range: "6-42/78", pen: 9, traits: ["Precise"], category: "Advanced"},
    {BTCode: "IS_PPC", name: "Heavy Particle Accelorator", code: "HPA", range: "6-18/36", pen: 9, traits: ["Haywire"], category: "Advanced"},
    {BTCode: "IS_ERPPC", name: "Heavy Particle Accelorator", code: "HPA", range: "0-24/42", pen: 9, traits: ["Haywire"], category: "Advanced"},
    {BTCode: "IS_Flamer", name: "Medium Flamer", code: "MFL", range: "0-6/9", pen: 4, traits: ["AE:3", "AI", "Fire: 3", "Spray"], category: "Ballistic"},
    {BTCode: "IS_AC2", name: "Light Rifle", code: "LRF", range: "12-24/48", pen: 7, traits: ["Precise"], category: "Ballistic"},
    {BTCode: "IS_AC5", name: "Heavy Rifle", code: "HRF", range: "12-14/48", pen: 9, traits: ["Precise"], category: "Ballistic"},
    {BTCode: "IS_AC10", name: "Light Snub Cannon", code: "LSC", range: "4-12/24", pen: 8, traits: ["AP:2", "AS"], category: "Ballistic"},
    {BTCode: "IS_AC20", name: "Heavy Snub Cannon", code: "HSC", range: "3-9/18", pen: 10, traits: ["AP:4", "AS"], category: "Ballistic"},
    {BTCode: "IS_MG", name: "Heavy Machine Gun", code: "HMG", range: "3-9/18", pen: 4, traits: ["AI", "Burst:2"], category: "Ballistic"},
    {BTCode: "IS_GR", name: "Medium Rail Gun", code: "MRG", range: "12-36/72", pen: 9, traits: ["AP:4", "AS"], category: "Advanced"},
    {BTCode: "IS_SRM2", name: "Light Anti-Vehicle Rocket Pack", code: "LRP", range: "6-18/36", pen: 7, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "IS_SRM4", name: "Medium Anti-Vehicle Rocket Pack", code: "MRP", range: "6-18/36", pen: 8, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "IS_SRM6", name: "Heavy Anti-Vehicle Rocket Pack", code: "HRP", range: "6-18/36", pen: 9, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "IS_LRM5", name: "Light Artillery Rockets", code: "LA", range: "18-36/72", pen: 7, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "IS_LRM10", name: "Medium Artillery Rockets", code: "MAR", range: "18-36/72", pen: 8, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "IS_LRM15", name: "Heavy Atrillery Rockets", code: "HAR", range: "18-36/72", pen: 9, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "IS_LRM20", name: "Very Heavy Artillery Rockets", code: "VHAR", range: "18-36/72", pen: 10, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "IS_UAC2", name: "Light Rifle", code: "LRF", range: "12-24/48", pen: 7, traits: ["Precise", "Burst: 1"], category: "Ballistic"},
    {BTCode: "IS_UAC5", name: "Heavy Rifle", code: "HRF", range: "12-14/48", pen: 9, traits: ["Precise", "Burst: 1"], category: "Ballistic"},
    {BTCode: "IS_UAC10", name: "Light Snub Cannon", code: "LSC", range: "4-12/24", pen: 8, traits: ["AP:2", "AS", "Burst: 1"], category: "Ballistic"},
    {BTCode: "IS_UAC20", name: "Heavy Snub Cannon", code: "HSC", range: "3-9/18", pen: 10, traits: ["AP:4", "AS", "Burst: 1"], category: "Ballistic"},
    {BTCode: "IS_LBX2", name: "Light Rifle", code: "LRF", range: "12-24/48", pen: 7, traits: ["Ammo: Precise", "Ammo: Spray Split"], category: "Ballistic"},
    {BTCode: "IS_LBX5", name: "Heavy Rifle", code: "HRF", range: "12-14/48", pen: 9, traits: ["Ammo: Precise", "Ammo: Spray Split"], category: "Ballistic"},
    {BTCode: "IS_LBX10", name: "Light Snub Cannon", code: "LSC", range: "4-12/24", pen: 8, traits: ["Ammo: AP2 AS", "Ammo: Spray Split 2"], category: "Ballistic"},
    {BTCode: "IS_LBX20", name: "Heavy Snub Cannon", code: "HSC", range: "3-9/18", pen: 10, traits: ["Ammo: AP4 AS", "Ammo: Spray Split 2"], category: "Ballistic"},
    {BTCode: "IS_RAC2", name: "Light Rotary Cannon", code: "LRC", range: "6-12/24", pen: 6, traits: ["Burst: 2", "Split 2"], category: "Ballistic"},
    {BTCode: "IS_RAC5", name: "Heavy Rotary Cannon", code: "HRC", range: "6-12/24", pen: 8, traits: ["Burst: 2", "Split 2"], category: "Ballistic"},
    {BTCode: "IS_SSRM2", name: "Light Anti-Vehicle Missile", code: "LVM", range: "6-18/36", pen: 5, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
    {BTCode: "IS_SSRM4", name: "Medium Anit-Vehicle Missile", code: "MVM", range: "6-18/36", pen: 6, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
    {BTCode: "IS_SSRM6", name: "Heavy Anti-Vehicle Missile", code: "HVM", range: "6-18/36", pen: 7, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
    // Clan
    {BTCode: "CLAN_SPL", name: "Very Very Light Pulse Laser", code: "VVLPL", range: "4-12/24", pen: 5, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "CLAN_MPL", name: "Very Light Pulse Laser", code: "VLPL", range: "6-18/36", pen: 8, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "CLAN_LPL", name: "Medium Pulse Laser", code: "MPL", range: "12-24/48", pen: 10, traits: ["AS", "AE:2", "Blast"], category: "Advanced"},
    {BTCode: "CLAN_ERSL", name: "Heavy Infantry Laser", code: "HIL", range: "0-24/42", pen: 5, traits: ["AI", "Burst: 1"], category: "Advanced"},
    {BTCode: "CLAN_ERML", name: "Very Light Laser Cannon", code: "VLLC", range: "2-30/54", pen: 7, traits: ["Precise"], category: "Advanced"},
    {BTCode: "CLAN_ERLL", name: "Medium Laser Cannon", code: "MLC", range: "6-42/78", pen: 9, traits: ["Precise"], category: "Advanced"},
    {BTCode: "CLAN_ERPPC", name: "Very Heavy Particle Accelorator", code: "VHPA", range: "0-24/42", pen: 10, traits: ["Haywire"], category: "Advanced"},
    {BTCode: "CLAN_Flamer", name: "Medium Flamer", code: "MFL", range: "0-6/9", pen: 4, traits: ["AE:3", "AI", "Fire: 3", "Spray"], category: "Ballistic"},
    {BTCode: "CLAN_MG", name: "Heavy Machine Gun", code: "HMG", range: "3-9/18", pen: 4, traits: ["AI", "Burst:2"], category: "Ballistic"},
    {BTCode: "CLAN_GR", name: "Medium Rail Gun", code: "MRG", range: "12-36/72", pen: 9, traits: ["AP:4", "AS"], category: "Advanced"},
    {BTCode: "CLAN_SRM2", name: "Light Anti-Vehicle Rocket Pack", code: "LRP", range: "6-18/36", pen: 7, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "CLAN_SRM4", name: "Medium Anti-Vehicle Rocket Pack", code: "MRP", range: "6-18/36", pen: 8, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "CLAN_SRM6", name: "Heavy Anti-Vehicle Rocket Pack", code: "HRP", range: "6-18/36", pen: 9, traits: ["AE:4"], category: "Ballistic, Indirect"},
    {BTCode: "CLAN_LRM5", name: "Light Artillery Rockets", code: "LA", range: "12-42/72", pen: 7, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "CLAN_LRM10", name: "Medium Artillery Rockets", code: "MAR", range: "12-42/72", pen: 8, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "CLAN_LRM15", name: "Heavy Atrillery Rockets", code: "HAR", range: "12-42/72", pen: 9, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "CLAN_LRM20", name: "Very Heavy Artillery Rockets", code: "VHAR", range: "12-42/72", pen: 10, traits: ["AE:5"], category: "Indirect"},
    {BTCode: "CLAN_UAC2", name: "Light Rifle", code: "LRF", range: "12-24/48", pen: 7, traits: ["Precise", "Burst: 1"], category: "Ballistic"},
    {BTCode: "CLAN_UAC5", name: "Heavy Rifle", code: "HRF", range: "12-14/48", pen: 9, traits: ["Precise", "Burst: 1"], category: "Ballistic"},
    {BTCode: "CLAN_UAC10", name: "Light Snub Cannon", code: "LSC", range: "4-12/24", pen: 8, traits: ["AP:2", "AS", "Burst: 1"], category: "Ballistic"},
    {BTCode: "CLAN_UAC20", name: "Heavy Snub Cannon", code: "HSC", range: "3-9/18", pen: 10, traits: ["AP:4", "AS", "Burst: 1"], category: "Ballistic"},
    {BTCode: "CLAN_LBX2", name: "Light Rifle", code: "LRF", range: "12-24/48", pen: 7, traits: ["Ammo: Precise", "Ammo: Spray Split"], category: "Ballistic"},
    {BTCode: "CLAN_LBX5", name: "Heavy Rifle", code: "HRF", range: "12-14/48", pen: 9, traits: ["Ammo: Precise", "Ammo: Spray Split"], category: "Ballistic"},
    {BTCode: "CLAN_LBX10", name: "Light Snub Cannon", code: "LSC", range: "4-12/24", pen: 8, traits: ["Ammo: AP2 AS", "Ammo: Spray Split 2"], category: "Ballistic"},
    {BTCode: "CLAN_LBX20", name: "Heavy Snub Cannon", code: "HSC", range: "3-9/18", pen: 10, traits: ["Ammo: AP4 AS", "Ammo: Spray Split 2"], category: "Ballistic"},
    {BTCode: "CLAN_SSRM2", name: "Light Anti-Vehicle Missile", code: "LVM", range: "6-18/36", pen: 5, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
    {BTCode: "CLAN_SSRM4", name: "Medium Anit-Vehicle Missile", code: "MVM", range: "6-18/36", pen: 6, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
    {BTCode: "CLAN_SSRM6", name: "Heavy Anti-Vehicle Missile", code: "HVM", range: "6-18/36", pen: 7, traits: ["AP1", "Guided", "Missile"], category: "Indirect"},
];